sequenceDiagram
    participant UI as UI (react component)
    participant Core as Core (pure state and logic)
    participant Tool as Tool (pure tool implementation)
    participant Canvas as Canvas (Konva canvas component)
    participant React as React (react binding)

    UI->>+Core: createDrawingEngine()
    Core-->>-UI: engine
    UI->>+Tool: createFreeDrawTool()
    Tool-->>-UI: tool
    UI->>+Canvas: KonvaDrawingCanvas(engine, tool)
        Canvas->>+React: useDrawing(engine)
        React-->>-Canvas: state
        Canvas-->>Canvas: updates canvas state (e.g. add points to line)
    Canvas-->>-UI: renders UI with canvas
